behavior_descriptors:
- velocity_y
- floor_contact
body_descriptors:
- relative_activity
- elongation
body_encoding: indirect
brain_descriptors:
- activations_dimensionality_reduction
controller: local
env_name: BridgeWalker-v0
episode_length: 200
fixed_body: false
flags:
  observe_time: false
  observe_voxel_vel: true
  observe_voxel_volume: true
frequency_cut_off: 0.5
grid_size: 10
iso_sigma: 0.005
jax: true
line_sigma: 0.05
max_env_size: 5
n_body_elements: 20
n_iterations: 4000
p_mut_body: 0.05
parents_size: 45
policy_hidden_layer_sizes: !!python/tuple
- 20
- 20
pop_size: 50
program_wrapper: true
qd_wrappers:
- velocity
- floor_contact
run_name: evobb_nn_brain
sampler: s1
seed: 12
skip: 5
solver: ne
