behavior_descriptors:
- velocity_y
- floor_contact
body_descriptors:
- relative_activity
- elongation
body_encoding: indirect
buffer_size: 79
controller: local
env_name: Hurdler-v0
episode_length: 200
fixed_body: false
fixed_outputs: true
flags:
  observe_time: false
  observe_voxel_vel: true
  observe_voxel_volume: true
frequency_cut_off: 0.5
genome_size: 151
graph_descriptors: function_arities
grid_size: 10
jax: true
max_env_size: 5
n_body_elements: 20
n_constants: 2
n_functions: 14
n_in: 29
n_in_env: 27
n_iterations: 4000
n_nodes: 50
n_out: 1
p_mut_body: 0.05
p_mut_functions: 0.1
p_mut_inputs: 0.1
p_mut_outputs: 0
parents_size: 45
pop_size: 50
program_state_size: 79
program_wrapper: true
qd_wrappers:
- velocity
- floor_contact
run_name: evobb_graph_behavior
sampler: s3
seed: 19
skip: 5
solver: cgp
